baseURL: https://omoltke.netlify.app/
languageCode: en-us
title: Portfolio website for Otto Moltke
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's do this
    subtitle: |-
      Feel free to explore this site to get to know more about me and my interests.
    title: Otto Moltke's Portfolio
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    formEmail: "/f/myyladel"
    email: 
      - email: omoltke.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 00 45 40 31 65 04
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: #
        text: #
        url: #
    social:
      - icon: #
        label: #
        url: #
      - icon: #
        label: #
        url: #
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/londonbschool/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/OMoltke
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/omoltke/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: '#'
    button2:
      - name: Contact
        url: 'mailto:omoltke.mfa2022@london.edu'
    links:
      - name: Home
        url: '#'
      - name: #
        url: #
      - name: About
        url: blogs/about
      - name:
        url: '#'
    menu: Menu
    subtitle: By Otto Moltke
    title: Personal Portfolio
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Experiences and achievements
        title: Resume
        url: blogs/cv
      - image: moritzmartinsawtwo.jpg
        subtitle: Making new friends while making an difference
        title: MFA Away Day
        url: blogs/experiences
      - image: drought.jpg
        subtitle: Science and politics
        title: Climate change - Data and opinion
        url: blogs/programming
      - image: moonpandalexington.jpg
        subtitle: A band you should check out!
        title: Moon Panda
        url: blogs/moonpanda
      - image: solarpanels.jpg
        subtitle: A feasibility study
        title: How much value can batteries create?
        url: blogs/solarbatteries
      - image:
        subtitle: Let's do it all again
        title: Back to the top
        url: '#'
  two:
    buttonText: Get Started
    enable: no
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
