---
title: "Working in R"
date: '2017-10-31T21:28:43-05:00'
description: ''
draft: no
image: theiceismelting.jpg
keywords: ''
slug: programming
categories:
- ''
- ''
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>The year before I started studying at London Business School, I worked for Danish energy company <a href="https://orsted.co.uk/">Ørsted</a>, which specialises in offshore wind. Ørsted was named <a href="https://orsted.co.uk/about-us/worlds-most-sustainable-energy-company?gclid=CjwKCAjw_L6LBhBbEiwA4c46ugeYtqek06uswZ7dyYGUeBn79XMwqFrNh09ZbyLPNVMg8Yp4EDJn1hoCVsEQAvD_BwE">world’s most for the 3rd year in a row</a> in 2021. I find renewable energy and the green transition in general very interesting. Therefore, I really enjoyed working with NASA’s data on <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a> as an indicator of climate change. On this site, I would like to take you through our work, as it shows both some interesting insights, but also a wide range of data wrangling and data illustration using R.</p>
<p>The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<div id="data-wrangling" class="section level2">
<h2>Data wrangling</h2>
<p>To define temperature anomalies we needed to have a reference, or base, period. NASA clearly states that this period is between 1951-1980.</p>
<p>We ran the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>Here, you should notice that, when using this function, we added two options: <code>skip</code> and <code>na</code>.</p>
<ol style="list-style-type: decimal">
<li>The <code>skip=1</code> option is there as the real data table only starts in Row 2, so we need to skip one row.</li>
<li><code>na = "***"</code> option informs R how missing observations in the spreadsheet are coded. When looking at the spreadsheet, you will see that missing data is coded as “***“. It is best to specify this here, as otherwise some of the data is not recognized as numeric data.</li>
</ol>
<p>For each month and year, the dataframe showed the deviation of temperature from the normal (expected). Further the dataframe was in wide format.</p>
<p>We had two objectives in this section:</p>
<ol style="list-style-type: decimal">
<li><p>Select the year and the twelve month variables from the <code>weather</code> dataset. We did not need the others (J-D, D-N, DJF, etc.) for this assignment.</p></li>
<li><p>Convert the dataframe from wide to ‘long’ format. We name the new dataframe as <code>tidyweather</code>, the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p></li>
</ol>
<pre class="r"><code>weather_new &lt;- weather %&gt;%
  select(Year:Dec) # We select only the year and months variables

tidyweather &lt;- weather_new %&gt;% 
  pivot_longer(cols = Jan:Dec,
               names_to = &quot;Month&quot;,
               values_to = &quot;delta&quot;)</code></pre>
<p>We inspect our dataframe. It should have three variables now, one each for</p>
<ol style="list-style-type: decimal">
<li>year,</li>
<li>month, and</li>
<li>delta, or temperature deviation.</li>
</ol>
<pre class="r"><code>tidyweather %&gt;% 
  head(n=6)</code></pre>
<pre><code>## # A tibble: 6 x 3
##    Year Month delta
##   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
## 1  1880 Jan   -0.35
## 2  1880 Feb   -0.51
## 3  1880 Mar   -0.23
## 4  1880 Apr   -0.3 
## 5  1880 May   -0.06
## 6  1880 Jun   -0.16</code></pre>
</div>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Now, we plotted the data using a time-series scatter plot, and added a trendline. To do that, we first needed to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values were plotted chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p><img src="/blogs/3_WorkinginR_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>In order to investigate whether the effect of increasing temperature more pronounced in some months, we used <code>facet_wrap()</code> to produce a seperate scatter plot for each month, again with a smoothing line. We needed to ensure that our graphs had human-readable labels using ‘labs’; that is, each month should be labeled “Jan”, “Feb”, “Mar”, not <code>1</code>, <code>2</code>, <code>3</code>.</p>
<p><img src="/blogs/3_WorkinginR_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a temperature anomaly, as difference form the base period of 1951-1980. The code below created a new data frame called <code>comparison</code> that grouped data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We removed data before 1880 and before using <code>filter</code>. Then, we used the <code>mutate</code> function to create a new variable <code>interval</code> which contained information on which period each observation belonged. We assigned the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we hac the <code>interval</code> variable, we coulc create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we were interested in. In order to group and colour the data by different time period, we set <code>fill</code> to <code>interval</code>.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with transparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p><img src="/blogs/3_WorkinginR_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we had been working with monthly anomalies. However, we were also interested in average annual anomalies. Therefore, we used <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # We use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta= mean(delta, na.rm = TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="/blogs/3_WorkinginR_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Our task was to construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package. The dataframe <code>comparison</code> had already grouped temperature anomalies according to time intervals; we were only interested in what was happening between 2011-present.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 

  filter(interval == &quot;2011-present&quot;) %&gt;% # choose the interval 2011-present
  summarise(mean_delta = mean(delta, na.rm = TRUE),
                         sd_delta = sd(delta, na.rm = TRUE),
                         count_delta = n(),
                         se_delta = sd_delta/sqrt(count_delta),
                         t_crit = qt(0.975, count_delta-1),
                         lower_ci = mean_delta - t_crit * se_delta,
                         upper_ci = mean_delta + t_crit * se_delta
            ) # calculate summary statistics for temperature deviation (delta) 
  # calculate mean, SD, count, SE, lower/upper 95% CI
  # what dplyr verb will you use? 

#print out formula_CI
formula_ci</code></pre>
<pre><code>## # A tibble: 1 x 7
##   mean_delta sd_delta count_delta se_delta t_crit lower_ci upper_ci
##        &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1       1.06    0.274         132   0.0239   1.98     1.01     1.11</code></pre>
<pre class="r"><code>set.seed(1234)


bootstrap_delta &lt;- comparison %&gt;%
  # Choose only  2011 - Present
  filter(interval == &quot;2011-present&quot;) %&gt;%
  # Specify the variable of interest
  specify(response = delta) %&gt;%
  # Generate a bunch of bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  # Find the median of each sample
  calculate(stat = &quot;mean&quot;)

# select 2011-present from the formula-calculated CIs
bootstrap_ci &lt;- bootstrap_delta %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)

bootstrap_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.11</code></pre>
<blockquote>
<p>So, what is the data showing us?</p>
</blockquote>
<p>Our original data shows that with 95% confidence, the true mean deviation in monthly temperature lies between 1.01-1.11 degrees. This does not mean that there is a 95% chance that the true mean lies in that interval, but it does mean that if you were to repeatedly calculate confidence intervals, 95% of these would contain the true mean monthly deviation in temperature. By randomly sampling observations based on the given dataset using the bootstrapping method, the data is showing us that with 95% confidence the monthly temperature between 2011 and present times is on average between 1.02 and 1.11 degrees higher than the historic average for that month in the base period from 1951 to 1980. Thus, the sampling confirms our confidence interval between 1.02 and 1.11. The confidence interval doesn’t contain 0 so we reject the null hypothesis that there is no deviation.</p>
</div>
</div>
<div id="global-warming-and-political-views-gss" class="section level1">
<h1>Global warming and political views (GSS)</h1>
<p><a href="https://www.pewresearch.org/2010/10/27/wide-partisan-divide-over-global-warming/">A 2010 Pew Research poll</a> asked 1,306 Americans, “From what you’ve read and heard, is there solid evidence that the average temperature on earth has been getting warmer over the past few decades, or not?”</p>
<p>In this exercise we analyze whether there are any differences between the proportion of people who believe the earth is getting warmer and their political ideology. As usual, from the <strong>survey sample data</strong>, we will use the proportions to estimate values of <em>population parameters</em>. The file has 2253 observations on the following 2 variables:</p>
<ul>
<li><code>party_or_ideology</code>: a factor (categorical) variable with levels Conservative Republican, Liberal Democrat, Mod/Cons Democrat, Mod/Lib Republican</li>
<li><code>response</code> : whether the respondent believes the earth is warming or not, or Don’t know/ refuse to answer</li>
</ul>
<pre class="r"><code>global_warming_pew &lt;- read_csv(here::here(&quot;data&quot;, &quot;global_warming_pew.csv&quot;))</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<pre class="r"><code>global_warming_pew %&gt;% 
  count(party_or_ideology, response)</code></pre>
<pre><code>## # A tibble: 12 x 3
##    party_or_ideology       response                          n
##    &lt;chr&gt;                   &lt;chr&gt;                         &lt;int&gt;
##  1 Conservative Republican Don&#39;t know / refuse to answer    45
##  2 Conservative Republican Earth is warming                248
##  3 Conservative Republican Not warming                     450
##  4 Liberal Democrat        Don&#39;t know / refuse to answer    23
##  5 Liberal Democrat        Earth is warming                405
##  6 Liberal Democrat        Not warming                      23
##  7 Mod/Cons Democrat       Don&#39;t know / refuse to answer    45
##  8 Mod/Cons Democrat       Earth is warming                563
##  9 Mod/Cons Democrat       Not warming                     158
## 10 Mod/Lib Republican      Don&#39;t know / refuse to answer    23
## 11 Mod/Lib Republican      Earth is warming                135
## 12 Mod/Lib Republican      Not warming                     135</code></pre>
<p>We will be constructing four 95% confidence intervals to estimate population parameters, for the % who believe that <strong>Earth is warming</strong>, according to their party or ideology. You can create the CIs using the formulas by hand, or use <code>prop.test()</code></p>
<pre class="r"><code>party_ci &lt;- global_warming_pew %&gt;% 
  filter(response != &quot;Don&#39;t know / refuse to answer&quot;) %&gt;%
  mutate(warm = response == &quot;Earth is warming&quot;) %&gt;% 
  group_by(party_or_ideology) %&gt;% 
  summarise(mean_warm = mean(warm, na.rm = TRUE),
                         sd_warm = sd(warm, na.rm = TRUE),
                         count_warm = n(),
                         se_warm = sd_warm/sqrt(count_warm),
                         t_crit = qt(0.975, count_warm-1),
                         lower_ci = mean_warm - t_crit * se_warm,
                         upper_ci = mean_warm + t_crit * se_warm
            )
  
party_ci</code></pre>
<pre><code>## # A tibble: 4 x 8
##   party_or_ideolo~ mean_warm sd_warm count_warm se_warm t_crit lower_ci upper_ci
##   &lt;chr&gt;                &lt;dbl&gt;   &lt;dbl&gt;      &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Conservative Re~     0.355   0.479        698  0.0181   1.96    0.320    0.391
## 2 Liberal Democrat     0.946   0.226        428  0.0109   1.97    0.925    0.968
## 3 Mod/Cons Democr~     0.781   0.414        721  0.0154   1.96    0.751    0.811
## 4 Mod/Lib Republi~     0.5     0.501        270  0.0305   1.97    0.440    0.560</code></pre>
<p>Does it appear that whether or not a respondent believes the earth is warming is independent of their party ideology?</p>
<blockquote>
<p>Looking at the four confidence intervals, we could see that none of them overlap, suggesting that opinion on wether or not a respondent believes the earth is warming <strong>is</strong> dependent on political ideology.</p>
</blockquote>
<p>Thus, we conclude our work with analysing climate change from a scientific perspective as well as the influence of political views’ impact on perception of climate change.</p>
<p>To dive deeper in to this topic, you may want to read on <a href="https://www.brookings.edu/research/the-challenging-politics-of-climate-change/">The challenging politics of climate change</a></p>
</div>
